version: "3.7"

services:
  neo4j:
        image: neo4j
        container_name: neo4j
        volumes:
            - ./neo4j/data:/data
        environment:
            NEO4J_AUTH: neo4j/clave
            NEO4J_BOLT_PORT_NUMBER: "7687"
            NEO4J_HTTP_PORT_NUMBER: "7474"
        ports:
            - 7687:7687 #Bolt
            - 7474:7474 #HTTP

  redis:
    container_name: redis
    image: redis
    hostname: redis
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    ##command: docker run --rm --name redis-commander -d \ -p 8081:8081 \ rediscommander/redis-commander:latest

  ## Config Servers
  config01:
    image: mongo:latest
    command: mongod --port 27017 --configsvr --replSet configserver   --oplogSize 16
    volumes:
      - ./scripts:/scripts
  config02:
    image: mongo:latest
    command: mongod --port 27017 --configsvr --replSet configserver   --oplogSize 16
    volumes:
      - ./scripts:/scripts

  ## Shards
  shard01a:
    image: mongo:latest
    command: mongod --port 27018 --shardsvr --replSet shard01   --oplogSize 16
    volumes:
      - ./scripts:/scripts
  shard01b:
    image: mongo:latest
    command: mongod --port 27018 --shardsvr --replSet shard01   --oplogSize 16
    volumes:
      - ./scripts:/scripts
  shard02a:
    image: mongo:latest
    command: mongod --port 27019 --shardsvr --replSet shard02   --oplogSize 16
    volumes:
      - ./scripts:/scripts
  shard02b:
    image: mongo:latest
    command: mongod --port 27019 --shardsvr --replSet shard02   --oplogSize 16
    volumes:
      - ./scripts:/scripts

  ## Router
  router:
    image: mongo:latest
    command: mongos --port 27017 --configdb configserver/config01:27017,config02:27017 --bind_ip_all
    ports:
      - "27001:27017"
    volumes:
      - ./scripts:/scripts
    depends_on:
      - config01
      - config02
      - shard01a
      - shard01b
      - shard02a
      - shard02b

  docker-hoster:
    image: dvdarias/docker-hoster
    depends_on:
      - config01
      - config02
      - shard01a
      - shard01b
      - shard02a
      - shard02b
      - router
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts

