version: '3'
services:
  mongodb_container:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    expose:
      - 27017
    restart: "no"
    command: ["/usr/bin/mongod", "--bind_ip_all", "--port", "27017"]
    volumes:
      - mongodb_data_container:/data/db
      - ./src/:/usr/src

volumes:
  mongodb_data_container: