spring: 
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ~
    url: "jdbc:mysql://localhost/pregunta3"
    username: userPHM
  jpa: 
    hibernate: 
      ddl-auto: create-drop
      format_sql: true
    open-in-view: false
    properties: 
      hibernate: 
        format_sql: false
    show-sql: true
  data:
       mongodb:
         database: pregunta3
         port: 27001
         repositories:
           enabled: true
  main:
    allow-bean-definition-overriding: true
