spring: 
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ~
    url: "jdbc:mysql://localhost/pregunta3"
    username: userPHM
  jpa: 
    hibernate: 
      ddl-auto: create-drop
      format_sql: true
    open-in-view: false
    properties: 
      hibernate: 
        format_sql: false
    show-sql: true
  data:
       mongodb:
         database: pregunta3
         port: 27001
         repositories:
           enabled: true
       neo4j:
         uri: bolt://localhost:7687
         username: neo4j
         password: clave

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 50000

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.data: DEBUG
    org.neo4j: DEBUG

